# Generated by Django 4.1.7 on 2023-03-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="start",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="performence",
            name="artist",
            field=models.ManyToManyField(
                related_name="performences", to="events.artist"
            ),
        ),
        migrations.AlterField(
            model_name="performence",
            name="end",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="performence",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performences",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="performence",
            name="start",
            field=models.DateTimeField(blank=True),
        ),
    ]
