services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:8000
    entrypoint: bash -c "./entrypoint.sh"
    env_file: .env
    volumes:
      - ./:/app/
    depends_on:
      db:
        condition: service_healthy

  celery:
    build:
      dockerfile: Dockerfile
      context: .
    entrypoint: celery -A core worker -l INFO
    env_file: .env
    volumes:
      - ./:/app/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:15.2
    ports:
      - 5432:5432
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
